export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const CHECK_TODO = 'CHECK_TODO'
export const FILTER_TODOS = 'FILTER_TODOS'
export const SWITCH_COMPLETE = 'SWITCH_COMPLETE'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
